FROM node:24-alpine
WORKDIR /app

COPY package*.json ./
COPY tsconfig*.json ./
COPY angular.json ./
COPY proxy.conf.json ./
COPY public ./public
RUN npm ci

EXPOSE 4200
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "2000"]
