services:
    db:
        image: postgres:16
        container_name: sertaccan_db
        restart: always
        ports:
            - "5432:5432" # Bilgisayarının 5432 portunu container'a yönlendirir
        environment:
            POSTGRES_USER: sertacn # Kullanıcı adı
            POSTGRES_PASSWORD: e3g6y11zb3 # Şifre
            POSTGRES_DB: sertaccan_db # Veritabanı adı
        volumes:
            - postgres_data:/var/lib/postgresql/data # Verilerin kalıcı olması için
    redis:
        image: redis:7
        container_name: sertaccan_redis
        restart: always
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        command: redis-server --appendonly yes
volumes:
    postgres_data:
    redis_data:
